---
# tasks file for slurm

- name: install epel-release
  dnf:
    name: epel-release
    state: present

- name: install required packages
  dnf:
    name: "{{ slurm_required_packages }}"
    state: present

- name: download slurm-{{ slurm_version }}
  ansible.builtin.get_url:
    url: https://download.schedmd.com/slurm/slurm-{{ slurm_version }}.tar.bz2
    dest: /tmp/slurm-{{ slurm_version }}.tar.bz2
    checksum: "{{ slurm_checksum }}"

- name: unarchive slurm-{{ slurm_version }}.tar.bz2
  ansible.builtin.unarchive:
    src: /tmp/slurm-{{ slurm_version }}.tar.bz2
    dest: /tmp
    remote_src: yes

- name: install slurm-{{ slurm_version }} to {{ slurm_prefix }}
  shell: |
    ./configure --prefix={{ slurm_prefix }} {{ slurm_additional_configure_options }}
    make
    make install
  args:
    chdir: /tmp/slurm-{{ slurm_version }}
    creates: "{{ slurm_prefix }}/bin"

- name: install pam_slurm_adopt
  shell: make install
  args:
    chdir: /tmp/slurm-{{ slurm_version }}/contribs/pam_slurm_adopt
    creates: /lib64/security/pam_slurm_adopt.la
  when: slurm_install_pam_slurm_adopt
