---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: rockylinux:8.8
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
